const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const { pathToFileURL } = require('node:url')
const base = process.env.ATLAS_TEST_URL || 'http://127.0.0.1:8780/factory/'
const root = path.resolve(__dirname, '..')
const output = path.join(root, 'exports', 'browser-qa-v2')
const errors = []
const results = []
const settle = page => page.waitForTimeout(300)

async function closeInspector(page) {
  if (await page.locator('#inspector').isVisible()) await page.locator('#close-inspector').click()
}
async function filesView(page) {
  await closeInspector(page)
  await page.locator('#view-nav [data-project-view="artifacts"]').click()
  await page.locator('#artifact-workspace').waitFor({ state: 'visible' })
}
async function workflowView(page) {
  await closeInspector(page)
  await page.locator('#view-nav [data-project-view="workflow"]').click()
  await page.locator('[data-select-stage]').first().waitFor({ state: 'visible' })
}
async function download(page, button, name) {
  const pending = page.waitForEvent('download', { timeout: 10000 })
  await button.click()
  const artifact = await pending
  const savedPath = path.join(output, name || artifact.suggestedFilename())
  await artifact.saveAs(savedPath)
  return { name: artifact.suggestedFilename(), bytes: await fs.readFile(savedPath), path: savedPath }
}
async function projectJson(page, name) {
  await filesView(page)
  const artifact = await download(page, page.locator('#export-config'), name)
  return { ...artifact, config: JSON.parse(artifact.bytes.toString('utf8')) }
}
async function importProject(page, artifact, { dirty = false, cancel = false, reject = false } = {}) {
  await page.locator('#import-file').setInputFiles({ name: artifact.name, mimeType: artifact.mimeType || 'application/json', buffer: artifact.bytes })
  if (dirty && !reject) {
    await page.locator('#confirm-dialog').waitFor({ state: 'visible' })
    await page.getByRole('button', { name: cancel ? 'Keep this session' : 'Replace project', exact: true }).click()
  }
  await settle(page)
}
function zipContents(bytes) {
  const files = []
  let offset = 0
  while (offset + 30 <= bytes.length && bytes.readUInt32LE(offset) === 0x04034b50) {
    assert.equal(bytes.readUInt16LE(offset + 8), 0, 'Atlas archives store ordinary text files')
    const length = bytes.readUInt32LE(offset + 18)
    const nameLength = bytes.readUInt16LE(offset + 26)
    const start = offset + 30 + nameLength + bytes.readUInt16LE(offset + 28)
    files.push({ path: bytes.subarray(offset + 30, offset + 30 + nameLength).toString('utf8'), content: bytes.subarray(start, start + length).toString('utf8') })
    offset = start + length
  }
  return files
}
async function noOverflow(page, label) {
  const size = await page.evaluate(() => ({ viewport: innerWidth, page: document.documentElement.scrollWidth }))
  assert.ok(size.page <= size.viewport + 1, `${label} has horizontal overflow: ${JSON.stringify(size)}`)
}
async function screenshot(page, name) { await page.screenshot({ path: path.join(output, name), fullPage: true }) }

async function run() {
  const engine = await import(pathToFileURL(path.join(root, 'factory/core.mjs')).href)
  await fs.mkdir(output, { recursive: true })
  const browser = await chromium.launch({ headless: true })
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true })
    const page = await context.newPage()
    page.on('pageerror', error => errors.push(`Page error: ${error.message}`))
    page.on('console', message => { if (message.type() === 'error') errors.push(`Console: ${message.text()}`) })
    page.on('requestfailed', request => { if (!request.url().startsWith('blob:') && !/ERR_ABORTED/.test(request.failure()?.errorText || '')) errors.push(`Request failed: ${request.url()} ${request.failure()?.errorText}`) })
    page.on('dialog', dialog => dialog.accept())
    await page.goto(base)
    await page.locator('#start-screen').waitFor({ state: 'visible' })
    assert.equal(await page.locator('[data-start-recipe]').count(), 3)
    assert.equal(await page.locator('#studio-layout').isVisible(), false)
    assert.equal(await page.locator('#download-project').isVisible(), false)
    assert.equal(await page.locator('#file-tree [data-file]').count(), 0)
    assert.equal(await page.evaluate(() => localStorage.getItem('workflow-atlas.factory.v2')), null)
    await noOverflow(page, 'desktop Start')
    await screenshot(page, 'desktop-start.png')
    results.push('A fresh session starts without a project, generated files or a Download action')

    for (const recipe of ['feasibility', 'feature-delivery', 'bugfix']) {
      await page.locator(`[data-start-recipe="${recipe}"]`).click()
      await page.locator('#brief-dialog').waitFor({ state: 'visible' })
      assert.equal(await page.locator('#brief-name').inputValue(), '')
      assert.equal(await page.locator('#brief-purpose').inputValue(), '')
      assert.equal(await page.locator('#brief-context').inputValue(), '')
      assert.equal(await page.locator('#brief-name').evaluate(element => element === document.activeElement), true)
      await page.getByRole('button', { name: 'I will fill this in later', exact: true }).click()
      await page.locator('#brief-dialog').waitFor({ state: 'hidden' })
      await page.locator('#studio-layout').waitFor({ state: 'visible' })
      assert.equal(await page.locator('#project-name').inputValue(), '')
      assert.equal(await page.locator('#project-purpose').inputValue(), '')
      const ids = await page.locator('[data-select-stage]').evaluateAll(elements => elements.map(element => element.dataset.selectStage))
      assert.deepEqual(ids, engine.getStages(recipe).map(stage => stage.id))
      const exported = await projectJson(page, `blank-${recipe}.json`)
      assert.deepEqual(exported.config, engine.createRecipe(recipe), `${recipe} contains template choices without fictional project facts`)
      assert.equal(exported.config.runtime.enabled, false)
      await page.locator('#new-project').click()
      await page.locator('#start-screen').waitFor({ state: 'visible' })
    }
    results.push('Three starting workflows offer a blank task brief that can be deferred without inventing project facts or runtime design')

    await page.locator('#start-screen [data-studio-action="examples"]').click()
    await page.locator('#examples-dialog').waitFor({ state: 'visible' })
    assert.match(await page.locator('#examples-dialog').innerText(), /fictional/i)
    await page.locator('[data-example="feasibility"]').click()
    const example = await projectJson(page, 'chosen-example.json')
    assert.deepEqual(example.config, engine.createExample('feasibility'))
    assert.match(await page.locator('#project-origin').innerText(), /example/i)
    await page.locator('#new-project').click()
    await page.locator('[data-start-recipe="feature-delivery"]').click()
    results.push('Worked examples are explicitly chosen and remain visibly fictional')

    const firstStage = engine.getStages('feature-delivery')[0].id
    const note = 'Check documented access rules before changing search behavior.'
    await page.locator('#brief-dialog').waitFor({ state: 'visible' })
    await page.locator('#brief-name').fill('Reviewed search feature')
    await page.locator('#brief-purpose').fill('Add a search filter and make its acceptance checks explicit.')
    await page.locator('#brief-context').fill(note)
    await page.locator('#brief-form button[type="submit"]').click()
    await page.locator('#brief-dialog').waitFor({ state: 'hidden' })
    await settle(page)
    assert.equal(await page.locator('#project-name').inputValue(), 'Reviewed search feature')
    assert.equal(await page.locator('#project-purpose').inputValue(), 'Add a search filter and make its acceptance checks explicit.')
    await page.locator(`[data-select-stage="${firstStage}"]`).click()
    await page.locator('#inspector').waitFor({ state: 'visible' })
    assert.equal(await page.locator(`[data-field="workflow.notes.${firstStage}"]`).inputValue(), note)
    await page.locator(`[data-field="workflow.bindings.${firstStage}.actorType"]`).selectOption('human')
    await page.locator(`[data-field="workflow.bindings.${firstStage}.actorName"]`).fill('Requirement owner')
    await settle(page)
    await page.locator('#open-knowledge-map').click()
    await page.locator('#knowledge-workspace').waitFor({ state: 'visible' })
    const frame = page.frameLocator('#knowledge-frame')
    await frame.locator('#knowledge-back').waitFor({ state: 'visible' })
    assert.equal(await page.locator('#knowledge-workspace').evaluate(element => Math.round(element.getBoundingClientRect().width)), 1440)
    await frame.locator('#knowledge-back').click()
    await page.locator('#inspector').waitFor({ state: 'visible' })
    assert.equal(await page.locator(`[data-field="workflow.notes.${firstStage}"]`).inputValue(), note)
    assert.equal(await page.locator(`[data-select-stage="${firstStage}"]`).getAttribute('aria-pressed'), 'true')
    assert.equal(await page.locator('#open-knowledge-map').evaluate(element => element === document.activeElement), true)
    results.push('Knowledge map uses the viewport and returns to the selected stage without losing edits')

    await page.locator(`[data-action="add-stage-evidence"][data-stage-id="${firstStage}"]`).click()
    await page.locator('[data-field="evidence.0.check"]').fill('The accepted requirement covers restricted access.')
    await page.locator('[data-field="evidence.0.expected"]').fill('The requirement states allowed and rejected search access.')
    assert.equal(await page.locator('[data-field="evidence.0.observed"]').inputValue(), '')
    await filesView(page)
    await page.locator('[data-file="WORKFLOW.md"]').click()
    assert.match(await page.locator('#file-preview').innerText(), /Requirement owner/)
    assert.ok((await page.locator('#file-preview').innerText()).includes(note))
    await page.locator('#artifact-search').fill('file-that-does-not-exist')
    assert.match(await page.locator('#artifact-search-status').innerText(), /No matching files/)
    await page.locator('#artifact-search').fill('')
    const current = await projectJson(page, 'reviewed-search.project.json')
    assert.equal(current.config.workflow.bindings[firstStage].actorType, 'human')
    assert.equal(current.config.evidence[0].stageId, firstStage)
    assert.equal(current.config.evidence[0].status, 'planned')
    assert.equal(current.config.evidence[0].observed, '')
    await screenshot(page, 'desktop-files.png')
    results.push('Ownership, instructions and planned evidence reach exact files without fabricated observations')

    await page.locator('#download-project').click()
    await page.locator('#download-dialog').waitFor({ state: 'visible' })
    assert.equal(await page.locator('#download-title').innerText(), 'Choose a useful download')
    assert.match(await page.locator('#download-review').innerText(), /not been exercised/)
    assert.equal(await page.locator('[data-output-kind="pack"]').isChecked(), true)
    await page.locator('[data-output-kind="blueprint"]').check()
    assert.ok(!(await page.locator('.download-inventory code').allTextContents()).some(value => value.startsWith('.github/')))
    assert.equal(await page.locator('#use-download-title').textContent(), 'Use the workflow blueprint')
    await page.locator('[data-output-kind="skill"]').check()
    await page.locator('#output-skill').selectOption('requirement-refinement')
    const focusedPaths = await page.locator('.download-inventory code').allTextContents()
    assert.ok(focusedPaths.includes('.github/skills/requirement-refinement/SKILL.md'))
    assert.ok(focusedPaths.includes('project.json'))
    assert.ok(focusedPaths.includes('PROJECT-ATLAS.html'))
    assert.ok(!focusedPaths.some(value => value.startsWith('.github/agents/')))
    assert.ok(!focusedPaths.includes('WORKFLOW.md'))
    assert.doesNotMatch(await page.locator('#download-use-guide').textContent(), /custom agent|public preview|tools list/i)
    await page.locator('[data-output-kind="pack"]').check()
    const pack = await download(page, page.locator('[data-studio-action="download-output"]'), 'reviewed-search.zip')
    const contents = zipContents(pack.bytes)
    assert.deepEqual(JSON.parse(contents.find(file => file.path === 'project.json').content), current.config)
    assert.ok(contents.some(file => file.path === 'PROJECT-ATLAS.html'))
    assert.ok(contents.some(file => file.path.endsWith('/SKILL.md')))
    const manifest = JSON.parse(contents.find(file => file.path === 'manifest.json').content)
    assert.equal(manifest.kind, 'pack')
    assert.equal(manifest.validation.hostExercised, false)
    assert.equal(manifest.validation.behaviorObserved, false)
    assert.equal(manifest.validation.improvementEstablished, false)
    assert.match(await page.locator('#download-result').innerText(), /downloaded\. Open INSTALL\.md first/)
    assert.equal(await page.locator('#use-download').getAttribute('open'), '')
    assert.equal(await page.locator('#use-download-title').evaluate(element => element === document.activeElement), true)
    await page.locator('[data-close-dialog="download-dialog"]').click()
    results.push('Output choices show distinct inventories and matching guides, then pack download retains exact decisions and honest validation claims')

    await page.locator('#project-name').fill('Unsaved decision')
    await settle(page)
    await importProject(page, current, { dirty: true, cancel: true })
    assert.equal(await page.locator('#project-name').inputValue(), 'Unsaved decision')
    await importProject(page, { name: 'broken.json', bytes: Buffer.from('{broken') }, { reject: true })
    assert.match(await page.locator('#toast').innerText(), /current project is unchanged/i)
    assert.equal(await page.locator('#project-name').inputValue(), 'Unsaved decision')
    await importProject(page, current, { dirty: true })
    assert.equal(await page.locator('#project-name').inputValue(), current.config.project.name)
    assert.deepEqual((await projectJson(page, 'json-roundtrip.json')).config, current.config)
    await importProject(page, { ...pack, name: 'reviewed-search.zip', mimeType: 'application/zip' })
    assert.deepEqual((await projectJson(page, 'zip-roundtrip.json')).config, current.config)
    await filesView(page)
    assert.equal(await page.locator('#opened-files-strip').isVisible(), true)
    const originals = await download(page, page.locator('#opened-files-strip [data-studio-action="download-opened-files"]'), 'opened-files.zip')
    const fileMap = files => Object.fromEntries(files.map(file => [file.path, file.content]))
    assert.deepEqual(fileMap(zipContents(originals.bytes)), fileMap(contents))
    results.push('Rejected and cancelled imports keep edits, JSON and ZIP reopen faithfully, and opened files remain unchanged')

    const html = await download(page, page.locator('#download-atlas'), 'reviewed-search.html')
    await importProject(page, { ...html, name: 'reviewed-search.html', mimeType: 'text/html' })
    assert.deepEqual((await projectJson(page, 'html-roundtrip.json')).config, current.config)
    results.push('Readable Project Atlas HTML reopens its project decisions')

    await page.locator('#project-details').click()
    await page.locator('#details-nav [data-goto="project"]').click()
    assert.equal(await page.locator('[data-field="project.host"]').isVisible(), true)
    await page.locator('#details-nav [data-goto="runtime"]').click()
    assert.equal(await page.locator('[data-field="runtime.enabled"]').isChecked(), false)
    await workflowView(page)
    await screenshot(page, 'desktop-workflow.png')
    await page.setViewportSize({ width: 320, height: 740 })
    await noOverflow(page, '320px workflow')
    await page.locator(`[data-select-stage="${firstStage}"]`).click()
    assert.equal(await page.locator('#inspector').getAttribute('aria-modal'), 'true')
    assert.equal(await page.locator('#studio-main').evaluate(element => element.inert), true)
    await page.keyboard.press('Escape')
    assert.equal(await page.locator('#inspector').isVisible(), false)
    assert.equal(await page.locator(`[data-select-stage="${firstStage}"]`).evaluate(element => element === document.activeElement), true)
    await filesView(page)
    await noOverflow(page, '320px Files')
    await screenshot(page, 'mobile-files.png')
    await page.locator('#theme-toggle').click()
    await noOverflow(page, '320px alternate theme')
    await page.locator('#open-help').click()
    assert.equal(await page.locator('#help-title').evaluate(element => element === document.activeElement), true)
    await page.keyboard.press('Escape')
    assert.equal(await page.locator('#help-dialog').isVisible(), false)
    results.push('Optional details, narrow focus isolation and Workflow and Files fit a 320px viewport')

    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.reload()
    await page.locator('#start-screen').waitFor({ state: 'visible' })
    assert.equal(await page.locator('#download-project').isVisible(), false)
    assert.equal(await page.evaluate(() => localStorage.getItem('workflow-atlas.factory.v2')), null)
    assert.equal(await page.evaluate(() => localStorage.getItem('workflow-atlas.theme')), null)
    results.push('Reload starts fresh without automatically storing project or theme choices')

    assert.deepEqual(errors, [], 'No browser errors or failed application requests')
    await fs.writeFile(path.join(output, 'results.json'), JSON.stringify({ passed: results, browserErrors: errors, checkedAt: new Date().toISOString() }, null, 2) + '\n')
    console.log(`PASS ${results.length} browser scenarios`)
    results.forEach(result => console.log(`  ${result}`))
    console.log(`Artifacts: ${output}`)
  } finally { await browser.close() }
}
run().catch(error => { console.error(error); if (errors.length) console.error(errors); process.exitCode = 1 })
