(() => {
  'use strict';
  const {nodes,sources}=window.TOPIC_DATA,byId=new Map(nodes.map(n=>[n.id,n])),categories=nodes.filter(n=>n.parent==='overview');
  const colors=['#77dfff','#8aaeff','#ffbf75','#b7a1ff','#68ddbd','#ff8fa8','#f0c96d','#78d5ed','#c5b8ff','#8bd8a4'];
  const names=['Workflows','Toolchain','Models & cost','Skills & roles','Requirements','Debt & coverage','Jev','Knowledge','Verification & evidence','Evaluation'];
  const positions=[[-82,49,4],[-109,-4,-9],[-74,-49,9],[-35,14,51],[-37,63,-42],[82,49,4],[109,-4,-9],[74,-49,9],[35,14,51],[37,63,-42]];
  const clusters=new Map((window.TOPIC_DATA.catalog?.clusters||[]).map(cluster=>[cluster.id,cluster]));
  const meta=new Map(categories.map((n,i)=>{const cluster=clusters.get(n.id);return [n.id,{color:cluster?.color||colors[i%10],short:cluster?.short||names[i]||n.title,position:cluster?.position||positions[i%10],index:i}];}));
  function categoryFor(id){let n=byId.get(id);const seen=new Set();while(n&&n.id!=='overview'&&!seen.has(n.id)){seen.add(n.id);if(n.parent==='overview')return n.id;n=byId.get(n.parent);}return null;}
  const colorFor=id=>meta.get(categoryFor(id))?.color||colors[0],children=id=>nodes.filter(n=>n.parent===id),descendants=id=>nodes.filter(n=>n.id!==id&&categoryFor(n.id)===id);
  const $=id=>document.getElementById(id),el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
  const topicKinds={concept:'Concept',capability:'Capability',technology:'Technology',practice:'Practice',example:'Worked example',reference:'Reference',procedure:'Procedure'};
  const kindLabel=n=>topicKinds[n.catalog?.kind]||'';
  const availableKinds=Object.keys(topicKinds).filter(kind=>nodes.some(n=>n.catalog?.kind===kind));
  document.querySelectorAll('.topic-filters').forEach(box=>{box.hidden=!availableKinds.length;const filter=box.querySelector('select');availableKinds.forEach(kind=>{const option=el('option','',topicKinds[kind]);option.value=kind;filter.append(option);});});
  const legacyTours={
    study:{name:'Configuration service study',ids:['construct-study','study-baseline','study-quality','study-contract','study-runtime','study-economics','study-experiment','study-decision','study-ticket-wording','study-scenarios']},
    architect:{name:'Architect briefing',ids:['overview','architecture','requirements-workflow','implementation-workflow','curation-workflow','task-contract','toolchain','pilot']},
    engineering:{name:'Engineering delivery',ids:['requirement-status','traceability','impact-skill','implementation-workflow','verification-loops','post-change-checks','qa-packet','eval-metrics']},
    curation:{name:'Country-data curation',ids:['applicability','temporal-scope','wikidata-statements','jev-support','candidate-isolation','provenance','jev-shadow']},
    cost:{name:'Cost control',ids:['routing','model-prices','context-selection','eager-skills','revision-cache','budgets','cost-per-result']}
  };
  const tours=Object.create(null),collections=window.TOPIC_DATA.catalog?.collections;
  for(const collection of Array.isArray(collections)?collections:Object.entries(legacyTours).map(([id,path])=>({id,title:path.name,nodeIds:path.ids}))){
    if(!collection.id||Object.hasOwn(tours,collection.id)||!collection.title||!Array.isArray(collection.nodeIds))continue;
    const ids=[...new Set(collection.nodeIds)].filter(id=>byId.has(id));if(!ids.length)continue;
    tours[collection.id]={name:collection.title,ids};
  }
  $('tour-select').replaceChildren(el('option','','Choose a path…'));$('tour-select').firstElementChild.value='';
  Object.entries(tours).forEach(([id,path])=>{const option=el('option','',path.name);option.value=id;$('tour-select').append(option);});
  const params=new URLSearchParams(location.search),embedded=params.get('embedded')==='1';
  const reducedMotion=matchMedia('(prefers-reduced-motion:reduce)'),initialTheme=['dark','light'].includes(params.get('theme'))?params.get('theme'):(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');
  let selected='overview',mode='read',view=matchMedia('(max-width:700px)').matches?'2d':'3d',graph=null,graphPromise=null,tour=null,tourIndex=0,search='',topicKind='all',toastTimer,mapFocus=embedded,rotation=false;
  document.body.dataset.embedded=String(embedded);
  $('knowledge-back').hidden=!embedded;
  if(embedded){const factoryLink=document.querySelector('[data-factory-link]');if(factoryLink)factoryLink.hidden=true;}
  function sendParent(message){if(embedded&&location.origin!=='null')window.parent.postMessage(message,location.origin);}
  let practiceContext=null;
  const readerPractice=el('div','practice-slot');readerPractice.id='reader-practice';readerPractice.hidden=true;document.querySelector('.reader-heading').append(readerPractice);
  const mapActions=el('div','map-selection-actions'),mapPractice=el('div','practice-slot');mapPractice.id='map-practice';mapPractice.hidden=true;$('read-selection').before(mapActions);mapActions.append(mapPractice,$('read-selection'));
  function acceptedPracticeContext(data){
    if(typeof data?.projectName!=='string'||data.projectName.length>200||!Array.isArray(data.actions)||data.actions.length>10)return null;
    const seen=new Set(),actions=[];
    for(const action of data.actions){
      if(!action||typeof action.topicId!=='string'||!byId.has(action.topicId)||seen.has(action.topicId)||typeof action.id!=='string'||!/^[a-z][a-z0-9:-]{1,80}$/.test(action.id)||typeof action.title!=='string'||!action.title.trim()||action.title.length>200||typeof action.reason!=='string'||action.reason.length>2000||typeof action.alreadyApplied!=='boolean')return null;
      seen.add(action.topicId);actions.push({topicId:action.topicId,id:action.id,title:action.title,reason:action.reason,alreadyApplied:action.alreadyApplied});
    }
    return {projectName:data.projectName,actions};
  }
  function renderPracticeLinks(){
    const action=practiceContext?.actions.find(action=>action.topicId===selected);
    for(const [slot,compact] of [[readerPractice,false],[mapPractice,true]]){
      slot.replaceChildren();slot.hidden=!action;if(!action)continue;
      const card=el('div','practice-link'+(compact?' practice-link-compact':''));card.setAttribute('role','group');card.setAttribute('aria-label','Guidance for '+(practiceContext.projectName||'the current workflow'));
      card.append(el('span','practice-project','FOR '+(practiceContext.projectName||'THE CURRENT WORKFLOW')),el('strong','practice-title',action.title));
      if(!compact)card.append(el('p','practice-reason',action.reason));
      const button=el('button','practice-review',action.alreadyApplied?'Already included':'Review for my workflow');button.type='button';button.disabled=action.alreadyApplied;button.dataset.practiceRequest=action.id;button.dataset.practiceTopic=action.topicId;
      if(compact)button.title=action.reason;
      card.append(button,el('span','practice-boundary',action.alreadyApplied?'Recorded in your project decisions.':'Preview the changes before adding this practice.'));
      slot.append(card);
    }
  }
  function restorePracticeFocus(data){
    requestAnimationFrame(()=>{
      const slot=mode==='explore'?mapPractice:readerPractice;
      const button=slot.querySelector('[data-practice-request]');
      if(selected===data.topicId&&button&&!button.disabled&&button.dataset.practiceRequest===data.actionId){button.focus({preventScroll:true});return;}
      (mode==='explore'?$('read-selection'):mode==='sources'?$('source-title'):$('reader-title')).focus({preventScroll:true});
    });
  }
  $('knowledge-back').addEventListener('click',()=>sendParent({type:'workflow-atlas:close-knowledge'}));
  const expanded=new Set(),readableText=new Map(nodes.map(n=>[n.id,[n.title,n.summary,...n.sections.map(s=>[s.label,s.text,...(s.items||[]),...(s.headers||[]),...(s.rows||[]).flat()].filter(Boolean).join(' ')),...n.refs.map(r=>sources[r]?.[0]||'')].join(' ')]));
  const searchText=new Map(nodes.map(n=>[n.id,[readableText.get(n.id),...(n.catalog?.aliases||[]),...(n.catalog?.domains||[])].join(' ')]));
  const sourceUses=new Map(Object.keys(sources).map(key=>[key,nodes.filter(n=>n.refs.includes(key))])),sourceTypes={guidance:'Documentation & guidance',standards:'Standards & frameworks',research:'Research',code:'Code repository',video:'Video'};
  function sourceType(url){
    const {hostname,pathname}=new URL(url);
    if(hostname==='youtu.be'||/^(?:[^.]+\.)*youtube\.com$/.test(hostname))return 'video';
    if(hostname==='github.com'||hostname==='www.github.com')return 'code';
    if(/^(?:[^.]+\.)*(?:nist\.gov|w3\.org|rfc-editor\.org|ietf\.org)$/.test(hostname)||hostname==='agentskills.io'&&/^\/specification\/?$/.test(pathname))return 'standards';
    if(/^(?:[^.]+\.)*(?:arxiv\.org|acm\.org|doi\.org)$/.test(hostname)||hostname==='research.google'&&/^\/pubs(?:\/|$)/.test(pathname))return 'research';
    return 'guidance';
  }
  function topicButton(n,cls='topic-button',label){const b=el('button',cls,label||n.title);b.type='button';b.dataset.topic=n.id;if(n.id===selected)b.setAttribute('aria-current','page');b.style.setProperty('--node-color',colorFor(n.id));return b;}
  function navChildren(parent){const group=el('div','category-children');children(parent).forEach(n=>{group.append(topicButton(n));if(children(n.id).length)group.append(navChildren(n.id));});return group;}
  function renderNav(){const q=search.toLocaleLowerCase().trim(),result=q||topicKind!=='all'?nodes.filter(n=>(topicKind==='all'||n.catalog?.kind===topicKind)&&(!q||searchText.get(n.id).toLocaleLowerCase().includes(q))).sort((a,b)=>Number(b.title.toLocaleLowerCase().includes(q))-Number(a.title.toLocaleLowerCase().includes(q))):null;
    $('nav-heading').textContent=result?q?'Search results':'Topics by type':'Topic clusters';$('nav-count').textContent=result?`${result.length} found`:categories.length;$('topic-search-count').textContent=result?`${result.length} matching topic${result.length===1?'':'s'}${topicKind==='all'?'':' · '+topicKinds[topicKind]}`:`Browse ${categories.length} clusters or search all ${nodes.length} topics.`;document.querySelectorAll('[data-clear-topics]').forEach(button=>{button.hidden=!result;button.setAttribute('aria-label','Clear topic search and type filter');});
    for(const target of [$('topic-nav'),$('mobile-nav')]){const scroll=target.scrollTop;target.replaceChildren();
      if(result){if(!result.length)target.append(el('p','empty-search','No matching topics. Try another term or choose All types.'));result.forEach(n=>{const b=topicButton(n,'search-result');b.replaceChildren(el('small','',[meta.get(categoryFor(n.id))?.short||'Overview',kindLabel(n)].filter(Boolean).join(' · ')),el('strong','',n.title));const prose=readableText.get(n.id),match=q?prose.toLocaleLowerCase().indexOf(q):-1,text=match>=0?prose:n.summary,start=Math.max(0,match-35);b.append(el('span','result-excerpt',(start?'…':'')+text.slice(start,start+135)+(text.length>start+135?'…':'')),el('span','search-result-action','Read topic →'));b.dataset.openReading='true';b.setAttribute('aria-label',n.title+'. '+(kindLabel(n)?kindLabel(n)+'. ':'')+'Read topic');target.append(b);});}
      else categories.forEach(n=>{const d=el('details','nav-cluster');d.open=expanded.has(n.id)||categoryFor(selected)===n.id;const s=el('summary');s.style.setProperty('--node-color',colorFor(n.id));s.append(el('span','color-dot'),el('span','category-name',meta.get(n.id).short),el('small','category-count',descendants(n.id).length));d.append(s);const group=navChildren(n.id);group.prepend(topicButton(n,'topic-button cluster-overview','Cluster overview'));d.append(group);d.addEventListener('toggle',()=>{if(d.open)expanded.add(n.id);else expanded.delete(n.id);});target.append(d);});target.scrollTop=scroll;
    }document.querySelectorAll('.nav-home,.nav-study,.mobile-shortcuts [data-topic]').forEach(b=>{if(b.dataset.topic===selected)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
  }
  function heading(id,label,box){const h=el('h2','',label);h.id=id;h.tabIndex=-1;box.append(h);const a=el('a','',label);a.href='#'+id;a.dataset.section=id;$('page-toc').append(a);}
  function renderScope(n){
    const details=$('topic-scope'),content=$('topic-scope-content');details.open=false;content.replaceChildren();
    for(const [label,value] of [['Applies when',n.catalog?.applicability],['Limits',n.catalog?.limits]])if(typeof value==='string'&&value.trim())content.append(el('dt','',label),el('dd','',value));
    const sourceStatus=n.catalog?.sourceStatus,reviewText=sourceStatus==='legacy'?'References retained. This catalogue migration did not recheck their claims.':sourceStatus==='reviewed'?`Scoped claims reviewed${n.catalog.reviewedOn?' on '+n.catalog.reviewedOn:''}. Fit for your project remains unverified.`:sourceStatus==='needs-review'?'Illustrative or unreviewed guidance. Confirm fit and supporting evidence.':'';
    if(reviewText)content.append(el('dt','','Source review'),el('dd','',reviewText));
    for(const claim of n.catalog?.claims||[]){
      if(typeof claim.text!=='string'||!claim.text.trim())continue;
      const detail=el('dd','scope-claim');detail.append(el('p','',claim.text));const links=el('div','scope-claim-sources');
      for(const sourceId of claim.sourceRefs||[]){const source=sources[sourceId];if(!source)continue;const link=el('a','',source[0]+' ↗');link.href=source[1];link.target='_blank';link.rel='noopener noreferrer';links.append(link);}
      if(links.childElementCount)detail.append(links);content.append(el('dt','',claim.sectionLabel?'Claim: '+claim.sectionLabel:'Scoped source claim'),detail);
    }
    if(n.catalog?.guidance==='selectable')content.append(el('dt','','Project use'),el('dd','','Available for project review when applicable. Review the proposed changes before adding it to your workflow.'));
    details.hidden=!content.childElementCount;
  }
  function renderHome(){const root=$('quick-start');root.replaceChildren();root.hidden=selected!=='overview';if(root.hidden)return;
    const start=el('section','study-feature');start.append(el('span','overline','START WITH THE PROCESS'),el('h2','','Connect steps, outputs and checks'),el('p','','Learn what happens next when work passes, needs correction or must stop. Use these patterns to guide your own workflow design.'));
    const startActions=el('div','feature-actions');startActions.append(topicButton(byId.get('workflow-patterns'),'primary-button','Read workflow patterns →'),topicButton(byId.get('requirements-workflow'),'text-button','Start with requirements →'));start.append(startActions);root.append(start);
    const section=el('section','home-section');section.append(el('span','overline','THE DEVELOPMENT LIFECYCLE'),el('h2','','From requirements to production'),el('p','','Find guidance for each part of delivery. Adapt the checks and examples to your project.'));const lifecycle=el('div','lifecycle');[['requirements-workflow','Requirements'],['architecture-decisions','Architecture'],['work-breakdown','Breakdown'],['implementation-workflow','Development'],['verification-loops','Verification'],['release-operations','Release & operations']].forEach(([id,label],i)=>{const b=topicButton(byId.get(id),'lifecycle-stop',label);b.prepend(el('small','',String(i+1).padStart(2,'0')));lifecycle.append(b);});section.append(lifecycle);root.append(section);
    if(Object.keys(tours).length){const guided=el('section','home-section');guided.append(el('span','overline','CONNECTED READING'),el('h2','','Follow a guided path'));const choices=el('div','guided-path-grid');Object.entries(tours).forEach(([id,path])=>{const button=el('button','guided-path-choice');button.type='button';button.dataset.tour=id;button.append(el('strong','',path.name),el('span','',`${path.ids.length} topics · Start path →`));choices.append(button);});guided.append(choices);root.append(guided);}
    const card=el('section','study-feature');card.append(el('span','overline','A WORKED CASE STUDY'),el('h2','','A decision-ready feasibility study'),el('p','','Use the configuration service example to understand an engineer-run process, assess quality and costs, then recommend what a build phase should do. Adapt the guidance to your own project.'));
    const chips=el('div','feature-tags');['Study, before build','Configuration service','Evidence → decision'].forEach(x=>chips.append(el('span','',x)));card.append(chips);const actions=el('div','feature-actions');actions.append(topicButton(byId.get('construct-study'),'primary-button','Open the ticket study →'));const t=el('button','text-button','Take the guided path →');t.type='button';t.dataset.tour='study';actions.append(t);card.append(actions);root.append(card);
    const path=el('div','study-path');[['study-baseline','01','Baseline'],['study-quality','02','Output quality'],['study-contract','03','Service shape'],['study-economics','04','Economics'],['study-decision','05','Decision']].forEach(([id,num,title])=>{const b=topicButton(byId.get(id),'path-stop');b.replaceChildren(el('span','',num),el('strong','',title));path.append(b);});root.append(path);
    const clusters=el('section','home-section');clusters.append(el('span','overline','EXPLORE BY SUBJECT'),el('h2','','Ten connected topic clusters'));const grid=el('div','cluster-grid');categories.forEach(n=>{const b=topicButton(n,'cluster-card');b.replaceChildren(el('span','cluster-number',String(meta.get(n.id).index+1).padStart(2,'0')),el('strong','',n.title),el('span','',`${descendants(n.id).length} topics · Open cluster →`));grid.append(b);});clusters.append(grid);root.append(clusters);
  }
  function renderReader(){const n=byId.get(selected),cat=categoryFor(selected);$('reader').style.setProperty('--category',colorFor(selected));const chain=[];let p=n;while(p){chain.unshift(p);p=byId.get(p.parent);}const crumbs=$('breadcrumbs');crumbs.replaceChildren();chain.slice(0,-1).forEach(x=>crumbs.append(topicButton(x,'breadcrumb-button',x.id==='overview'?'Atlas':meta.get(x.id)?.short||x.title),el('span','','/')));crumbs.append(el('span','breadcrumb-current',selected==='overview'?'Overview':cat===selected?meta.get(cat).short:'Topic'));
    $('reader-kicker').textContent=selected==='overview'?'KNOWLEDGE ATLAS':selected==='construct-study'||n.parent==='construct-study'?'REFERENCE TO CONFIGURATION · WORKED CASE STUDY':n.parent==='overview'?'TOPIC CLUSTER':meta.get(cat)?.short;
    $('reader-title').textContent=n.title;$('reader-summary').textContent=n.summary;const metadata=$('reader-meta');metadata.replaceChildren(el('span','basis-badge',n.basis),el('span','confidence-label','Confidence: '+n.confidence));if(kindLabel(n))metadata.prepend(el('span','topic-kind-badge',kindLabel(n)));if(n.refs.length){const a=el('a','evidence-shortcut',`${n.refs.length} source${n.refs.length===1?'':'s'} ↓`);a.href='#source-evidence';a.dataset.section='source-evidence';metadata.append(a);}renderScope(n);
    $('page-toc').replaceChildren();renderHome();const content=$('reader-content');content.replaceChildren();if(selected==='construct-study'){const path=el('div','study-chapter-links');children(selected).forEach((x,i)=>{const b=topicButton(x,'chapter-link');b.prepend(el('span','',String(i+1).padStart(2,'0')));path.append(b);});content.append(path);}if(selected==='study-contract'){const flow=el('section','study-flow');flow.append(el('span','overline','ILLUSTRATIVE FLOW TO ASSESS'));const steps=el('div','flow-steps');[['study-baseline','Describe / import'],['study-runtime','Generate a draft'],['study-quality','Validate the output'],['study-decision','Accept the artifact']].forEach(([id,label],i)=>{const b=topicButton(byId.get(id),'flow-stop',label);b.prepend(el('small','',String(i+1).padStart(2,'0')+' →'));steps.append(b);});flow.append(steps,el('p','','Saving, applying and executing are separate actions. Accepting a generated artifact does not, by itself, authorize activation.'));content.append(flow);}
    n.sections.forEach((s,i)=>{const box=el('section','content-section');heading('section-'+i,s.label,box);if(s.type==='p')box.append(el('p','',s.text));if(s.type==='code'){const pre=el('pre');pre.append(el('code','',s.text));box.append(pre);}if(s.type==='list'||s.type==='steps'){const list=el(s.type==='steps'?'ol':'ul');s.items.forEach(x=>list.append(el('li','',x)));box.append(list);}if(s.type==='table'){const wrap=el('div','table-wrap');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label',s.label+' table; scroll horizontally if needed');const table=el('table'),head=el('thead'),tr=el('tr');s.headers.forEach(x=>{const th=el('th','',x);th.scope='col';tr.append(th);});head.append(tr);const body=el('tbody');s.rows.forEach(row=>{const r=el('tr');row.forEach((v,j)=>{const cell=el(j?'td':'th','',v);if(!j)cell.scope='row';r.append(cell);});body.append(r);});table.append(head,body);wrap.append(table);box.append(wrap);}content.append(box);});
    const src=$('reader-sources');src.replaceChildren();src.hidden=!n.refs.length;if(n.refs.length){heading('source-evidence','Source evidence',src);src.append(el('p','section-intro','Read the original material behind this topic. Recommendations and project assumptions still need local validation.'));n.refs.forEach(key=>{const [title,url]=sources[key];const a=el('a','source-link');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.append(el('span','source-domain',new URL(url).hostname),el('strong','',title),el('span','source-arrow','↗'));src.append(a);});}
    const rel=$('reader-related');rel.replaceChildren();const connected=[...new Set([...children(selected).map(x=>x.id),...n.related])];rel.hidden=!connected.length;if(connected.length){heading('connected-topics','Connected topics',rel);const links=el('div','related-links');connected.forEach(id=>{if(byId.has(id))links.append(topicButton(byId.get(id),'related-link'));});rel.append(links);}
    const foot=$('reader-next');foot.replaceChildren();const study=tours.study?.ids||[],seq=study.includes(selected)?study:cat?[cat,...descendants(cat).map(x=>x.id)]:[],at=seq.indexOf(selected);if(at>0){const b=topicButton(byId.get(seq[at-1]),'continue-button');b.prepend(el('small','','← Previous topic'));foot.append(b);}if(at>=0&&at<seq.length-1){const b=topicButton(byId.get(seq[at+1]),'continue-button');b.prepend(el('small','','Next topic →'));foot.append(b);}document.title=n.title+' · Workflow Atlas';renderPracticeLinks();
  }
  function renderFlat(){const cat=categoryFor(selected),shown=cat?[byId.get(cat),...descendants(cat)]:categories,root=$('flat-map');root.replaceChildren();root.classList.toggle('cluster-overview',!cat);shown.forEach(n=>{const b=topicButton(n,'map-card');b.replaceChildren(el('span','map-card-category',[n.parent==='overview'?'CLUSTER':meta.get(categoryFor(n.id)).short.toUpperCase(),kindLabel(n)].filter(Boolean).join(' · ')),el('strong','',n.title),el('span','',n.summary));root.append(b);});const list=$('map-topic-list');list.replaceChildren();nodes.forEach(n=>list.append(topicButton(n,'map-list-button')));document.querySelector('.map-index summary').textContent=`Browse all ${nodes.length} topics as a list`;}
  function mapHeading(){const cat=categoryFor(selected),n=byId.get(selected);$('map-eyebrow').textContent=cat?'FOCUSED KNOWLEDGE CLUSTER':'TEN CONNECTED KNOWLEDGE CLUSTERS';$('map-title').textContent=cat?byId.get(cat).title:'Explore the Knowledge Atlas';$('map-current-title').textContent=n.title;['read-map-topic','read-selection'].forEach(id=>$(id).setAttribute('aria-label','Read topic: '+n.title));$('map-selection-title').textContent=n.title;$('map-selection-summary').textContent=n.summary;$('map-selection-evidence').textContent=`${kindLabel(n)?kindLabel(n)+' · ':''}${n.basis} · Confidence: ${n.confidence} · ${n.refs.length} linked source${n.refs.length===1?'':'s'}`;}
  function updateState(){window.ATLAS_STATE={selected,category:categoryFor(selected),mode,view,tour:tour?.name||null,topics:nodes.length,sources:Object.keys(sources).length,embedded,mapFocus,theme:document.body.dataset.theme,rotation,reducedMotion:reducedMotion.matches,topicKind};}
  function clearTopicFilters(){search='';topicKind='all';$('topic-search').value=$('mobile-search').value='';$('topic-kind').value=$('mobile-topic-kind').value='all';renderNav();updateState();}
  function focusReader(){requestAnimationFrame(()=>{$('reader-title').focus({preventScroll:true});$('reader').scrollIntoView({block:'start',behavior:'instant'});});}
  function select(id,options={}){if(!byId.has(id))id='overview';if(tour&&!options.fromTour)exitTour();selected=id;renderNav();renderReader();renderFlat();mapHeading();graph?.select(id);if(!options.fromHash&&location.hash.slice(1)!==id)history.pushState({topic:id},'', '#'+id);if($('topics-dialog').open)$('topics-dialog').close();if(mode==='sources')setMode('read',false);if(options.focus!==false){if(mode==='read')focusReader();else $('read-map-topic').focus({preventScroll:true});}$('selection-announcement').textContent='Selected '+byId.get(id).title;updateState();}
  function ensureGraph(){if(graphPromise)return graphPromise;$('map-loading').hidden=false;graphPromise=import('./graph.mjs').then(({mountGraph})=>{graph=mountGraph({container:$('scene-canvas'),labels:$('scene-labels'),stage:$('graph-stage'),nodes,meta,byId,categoryFor,colorFor,onSelect:id=>select(id,{focus:false}),onHover:n=>{$('hover-caption').hidden=!n;if(n)$('hover-caption').textContent=n.title;}});graph.setTheme(document.body.dataset.theme);graph.setRotation(rotation);graph.select(selected,{instant:true});graph.setActive(mode==='explore'&&view==='3d');$('map-loading').hidden=true;document.body.dataset.graph='ready';}).catch(()=>{$('map-loading').hidden=true;document.body.dataset.graph='fallback';document.querySelector('[data-view="3d"]').disabled=true;setView('2d');toast('3D is unavailable here. Browse every topic with the topic cards or topic list.');});return graphPromise;}
  function setView(next){view=next;$('scene-canvas').hidden=view!=='3d';$('scene-labels').hidden=view!=='3d';$('flat-map').hidden=view!=='2d';['zoom-in','zoom-out','rotate-left','rotate-right','map-rotation'].forEach(id=>$(id).hidden=view==='2d');document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));graph?.setActive(mode==='explore'&&view==='3d');$('map-hint').textContent=view==='3d'?'Drag to rotate. Use + / − to zoom. Tab to topic buttons, or browse the full topic list.':'Select a card to explore its cluster. The full topic list is below.';if(mode==='explore'&&view==='3d')ensureGraph();else $('map-loading').hidden=true;updateState();}
  function setMapFocus(value){mapFocus=value;document.body.dataset.mapFocus=String(mapFocus);$('map-focus').setAttribute('aria-expanded',String(!mapFocus));$('map-focus').textContent=mapFocus?'Show reading panel ↙':'Focus map ↗';$('reading-layout').hidden=mode==='sources'||mode==='explore'&&mapFocus;updateState();}
  function setRotation(value){rotation=Boolean(value)&&!reducedMotion.matches;graph?.setRotation(rotation);$('map-rotation').textContent=rotation?'Pause rotation':'Start rotation';$('map-rotation').disabled=reducedMotion.matches;$('map-rotation').title=reducedMotion.matches?'Automatic rotation is off because reduced motion is enabled':'Rotation pauses while a topic button has keyboard focus';updateState();}
  function setMode(next,focus=true){mode=next;document.body.dataset.mode=mode;document.querySelectorAll('.mode-nav [data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('landscape').hidden=mode!=='explore';$('source-library').hidden=mode!=='sources';$('reading-layout').hidden=mode==='sources'||mode==='explore'&&mapFocus;if(mode==='explore'){setView(view);renderFlat();if(focus)$('landscape').scrollIntoView({block:'start',behavior:'instant'});}else{graph?.setActive(false);if(mode==='sources'){renderSources();if(focus){$('source-title').focus({preventScroll:true});$('source-library').scrollIntoView({block:'start',behavior:'instant'});}}else if(focus)focusReader();}updateState();}
  function renderSources(){const q=$('source-search').value.toLocaleLowerCase().trim(),filter=$('source-filter').value,root=$('source-cards');root.replaceChildren();const entries=Object.entries(sources).filter(([,v])=>(filter==='all'||sourceType(v[1])===filter)&&(v[0]+' '+new URL(v[1]).hostname).toLocaleLowerCase().includes(q));$('source-count').textContent=`${entries.length} of ${Object.keys(sources).length} sources`;if(!entries.length)root.append(el('p','empty-search','No matching sources. Try another term or source type.'));entries.forEach(([key,[title,url]])=>{const card=el('article','source-card');card.append(el('span','overline',sourceTypes[sourceType(url)]));const a=el('a','source-card-title',title+' ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';card.append(a,el('p','source-domain',new URL(url).hostname));const uses=sourceUses.get(key),list=el('div','source-topic-links');list.append(el('small','',`Used in ${uses.length} topic${uses.length===1?'':'s'}`));uses.slice(0,3).forEach(n=>list.append(topicButton(n,'source-topic')));if(uses.length>3){const d=el('details','source-more');d.append(el('summary','',`Show ${uses.length-3} more`));uses.slice(3).forEach(n=>d.append(topicButton(n,'source-topic')));list.append(d);}card.append(list);root.append(card);});}
  function tourOffset(){document.documentElement.style.setProperty('--tour-offset',$('tour-bar').hidden?'0px':($('tour-bar').getBoundingClientRect().height+25)+'px');}
  function showTourStep(){setMode('read',false);select(tour.ids[tourIndex],{fromTour:true});$('tour-bar').hidden=false;$('tour-name').textContent=tour.name;$('tour-step').textContent=`${tourIndex+1} / ${tour.ids.length} · ${byId.get(tour.ids[tourIndex]).title}`;$('tour-previous').disabled=tourIndex===0;$('tour-next').textContent=tourIndex===tour.ids.length-1?'Finish':'Next →';tourOffset();}
  function startTour(key){if(!tours[key])return;tour=tours[key];tourIndex=0;showTourStep();}function exitTour(){const restore=$('tour-bar').contains(document.activeElement);tour=null;$('tour-bar').hidden=true;tourOffset();updateState();if(restore)focusReader();}
  function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2600);}
  document.addEventListener('click',event=>{const b=event.target.closest('[data-topic],[data-tour],[data-section]');if(!b)return;if(b.dataset.topic){if(b.dataset.openReading==='true')setMode('read',false);select(b.dataset.topic);}else if(b.dataset.tour)startTour(b.dataset.tour);else{event.preventDefault();const dest=$(b.dataset.section);dest?.scrollIntoView({block:'start',behavior:'instant'});dest?.focus({preventScroll:true});}});
  document.querySelectorAll('.mode-nav [data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
  ['topic-search','mobile-search'].forEach(id=>$(id).addEventListener('input',e=>{search=e.target.value;$('topic-search').value=$('mobile-search').value=search;renderNav();}));
  ['topic-kind','mobile-topic-kind'].forEach(id=>$(id).addEventListener('change',e=>{topicKind=e.target.value;$('topic-kind').value=$('mobile-topic-kind').value=topicKind;renderNav();updateState();}));document.querySelectorAll('[data-clear-topics]').forEach(button=>button.addEventListener('click',()=>{clearTopicFilters();($('topics-dialog').open?$('mobile-search'):$('topic-search')).focus();}));
  $('source-search').addEventListener('input',renderSources);$('source-filter').addEventListener('change',renderSources);
  $('mobile-topics').addEventListener('click',()=>{$('topics-dialog').showModal();$('mobile-search').focus();});$('close-topics').addEventListener('click',()=>$('topics-dialog').close());$('topics-dialog').addEventListener('click',e=>{if(e.target===$('topics-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
  $('start-tour').addEventListener('click',()=>{const key=$('tour-select').value;if(key)startTour(key);else $('tour-select').focus();});$('tour-previous').addEventListener('click',()=>{if(tourIndex>0){tourIndex--;showTourStep();}});$('tour-next').addEventListener('click',()=>{if(tourIndex<tour.ids.length-1){tourIndex++;showTourStep();}else{exitTour();toast('Path complete. Explore connected topics or review the sources.');}});$('tour-exit').addEventListener('click',exitTour);
  ['read-map-topic','read-selection'].forEach(id=>$(id).addEventListener('click',()=>setMode('read')));$('overview-button').addEventListener('click',()=>select('overview',{focus:false}));$('zoom-in').addEventListener('click',()=>graph?.zoom(.8));$('zoom-out').addEventListener('click',()=>graph?.zoom(1.25));$('rotate-left').addEventListener('click',()=>graph?.rotate(-1));$('rotate-right').addEventListener('click',()=>graph?.rotate(1));$('map-focus').addEventListener('click',()=>setMapFocus(!mapFocus));$('map-rotation').addEventListener('click',()=>setRotation(!rotation));reducedMotion.addEventListener('change',()=>setRotation(false));document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();setMode('read',false);select('overview');});document.querySelector('.skip-link').addEventListener('click',e=>{e.preventDefault();setMode('read',false);focusReader();});
  $('copy-link').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Topic link copied');}catch{toast('Copy this topic’s link from the address bar.');}});
  function setTheme(theme,notify=false){if(!['light','dark'].includes(theme))return;document.body.dataset.theme=theme;$('theme-toggle').setAttribute('aria-checked',String(theme==='dark'));graph?.setTheme(theme);updateState();if(notify)sendParent({type:'workflow-atlas:theme',theme});}
  $('theme-toggle').addEventListener('click',()=>setTheme(document.body.dataset.theme==='dark'?'light':'dark',true));setTheme(initialTheme);
  window.addEventListener('message',event=>{if(!embedded||event.origin!==location.origin||event.source!==window.parent)return;if(event.data?.type==='workflow-atlas:theme'&&['light','dark'].includes(event.data.theme))setTheme(event.data.theme);if(event.data?.type==='workflow-atlas:practice-context'){practiceContext=acceptedPracticeContext(event.data);renderPracticeLinks();}if(event.data?.type==='workflow-atlas:practice-review-closed')restorePracticeFocus(event.data);});
  document.addEventListener('click',event=>{const button=event.target.closest('[data-practice-request]');if(!button||button.disabled)return;const action=practiceContext?.actions.find(action=>action.topicId===selected&&action.topicId===button.dataset.practiceTopic&&action.id===button.dataset.practiceRequest&&!action.alreadyApplied);if(action)sendParent({type:'workflow-atlas:practice-request',actionId:action.id,topicId:action.topicId});});
  function hashTopic(){let id='overview';try{id=decodeURIComponent(location.hash.slice(1))||id;}catch{}return byId.has(id)?id:'overview';}window.addEventListener('hashchange',()=>select(hashTopic(),{fromHash:true}));window.addEventListener('popstate',()=>{if(hashTopic()!==selected)select(hashTopic(),{fromHash:true});});
  document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.activeElement.isContentEditable){e.preventDefault();if(mode==='sources')$('source-search').focus();else if(innerWidth<=1000||mode==='explore'&&mapFocus){if(!$('topics-dialog').open)$('topics-dialog').showModal();$('mobile-search').focus();}else $('topic-search').focus();}if(e.key!=='Escape'||$('topics-dialog').open)return;if(search||topicKind!=='all'){e.preventDefault();clearTopicFilters();return;}if(mode==='sources'&&$('source-search').value){e.preventDefault();$('source-search').value='';renderSources();return;}if(embedded){e.preventDefault();sendParent({type:'workflow-atlas:close-knowledge'});}});
  new ResizeObserver(tourOffset).observe($('tour-bar'));
  $('atlas-count').textContent=`${nodes.length} topics · ${Object.keys(sources).length} sources`;setMapFocus(mapFocus);setRotation(false);setView(view);select(hashTopic(),{fromHash:true,focus:false});setMode(['read','explore','sources'].includes(params.get('view'))?params.get('view'):embedded?'explore':'read',false);
  sendParent({type:'workflow-atlas:knowledge-ready'});
})();
